default: &default
  adapter: postgresql
  min_messages: warning
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: subscribem_development

test:
  <<: *default
  database: subscribem_test
